### ISSUE TITLE
Unknown type name 'RCTCallableJSModules'

### ISSUE THREAD

**Issue by dev-john-nguyen** [agencyenterprise/react-native-health#323]
I get this error with the most recent release. Using IOS deployment 11.

<img width="1180" alt="image" src="https://github.com/agencyenterprise/react-native-health/assets/36948494/33962b69-8119-4795-b2d1-29d3bed6b38b">

**Comment by dev-john-nguyen** [comment]
React Native was outdated

**Comment by ErrorNone** [comment]
I have same bug(

**Comment by Rk5422686** [comment]
I encountered a similar issue. Initially, my React Native version was 0.62.3. Upon upgrading to 0.67.3, the problem was resolved. This was possible because the RCTCallableJSModules API for NativeModules was introduced in React Native version 0.66.0. Thus, to address this issue, it's necessary to upgrade your app to version 0.67 or later.
